-- Configuracion completa de Supabase para ELKY Studios.
-- Este script es idempotente: se puede ejecutar de nuevo sin duplicar recursos.

begin;

-- Cuenta administrativa autorizada:
-- javiercito_virgo1@hotmail.com
-- UUID: 69770c28-7c21-4edb-8656-9198fbd02df4

create table if not exists public.site_content (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_content_versions (
  id bigint generated by default as identity primary key,
  content_id text not null default 'main',
  data jsonb not null,
  reason text not null default 'Copia automatica',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.pending_reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  event text,
  event_type text,
  package text,
  text text not null,
  rating smallint not null check (rating between 1 and 5),
  photo text not null default '',
  date date not null default current_date,
  status text not null default 'pending'
    check (status in ('pending', 'published', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  client_name text not null,
  email text,
  phone text,
  event_type text,
  message text,
  event_date date,
  year integer,
  month integer check (month between 0 and 11),
  day integer check (day between 1 and 31),
  status text not null default 'pending',
  submitted_at timestamptz not null default now()
);

create index if not exists pending_reviews_status_created_at_idx
  on public.pending_reviews (status, created_at desc);

create index if not exists site_content_versions_content_created_at_idx
  on public.site_content_versions (content_id, created_at desc);

create index if not exists contact_requests_status_submitted_at_idx
  on public.contact_requests (status, submitted_at desc);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'elky-studios',
  'elky-studios',
  true,
  314572800,
  array['image/jpeg', 'image/png', 'image/webp', 'video/mp4']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

grant usage on schema public to anon, authenticated;
grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;
grant select, insert, delete on public.site_content_versions to authenticated;
grant insert on public.pending_reviews to anon, authenticated;
grant select, update, delete on public.pending_reviews to authenticated;
grant insert on public.contact_requests to anon, authenticated;
grant select, update, delete on public.contact_requests to authenticated;
grant usage, select on sequence public.pending_reviews_id_seq to anon, authenticated;
grant usage, select on sequence public.contact_requests_id_seq to anon, authenticated;
grant usage, select on sequence public.site_content_versions_id_seq to authenticated;

alter table public.site_content enable row level security;
alter table public.site_content_versions enable row level security;
alter table public.pending_reviews enable row level security;
alter table public.contact_requests enable row level security;

drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert site content" on public.site_content;
create policy "Admins can insert site content"
on public.site_content for insert
to authenticated
with check (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can update site content" on public.site_content;
create policy "Admins can update site content"
on public.site_content for update
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid)
with check (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can delete site content" on public.site_content;
create policy "Admins can delete site content"
on public.site_content for delete
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can create content versions" on public.site_content_versions;
create policy "Admins can create content versions"
on public.site_content_versions for insert
to authenticated
with check (
  auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid
  and created_by = auth.uid()
);

drop policy if exists "Admins can read content versions" on public.site_content_versions;
create policy "Admins can read content versions"
on public.site_content_versions for select
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can delete content versions" on public.site_content_versions;
create policy "Admins can delete content versions"
on public.site_content_versions for delete
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Public can submit reviews" on public.pending_reviews;
create policy "Public can submit reviews"
on public.pending_reviews for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "Admins can read reviews" on public.pending_reviews;
create policy "Admins can read reviews"
on public.pending_reviews for select
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can update reviews" on public.pending_reviews;
create policy "Admins can update reviews"
on public.pending_reviews for update
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid)
with check (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can delete reviews" on public.pending_reviews;
create policy "Admins can delete reviews"
on public.pending_reviews for delete
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Public can submit contact requests" on public.contact_requests;
create policy "Public can submit contact requests"
on public.contact_requests for insert
to anon, authenticated
with check (status = 'pending');

drop policy if exists "Admins can read contact requests" on public.contact_requests;
create policy "Admins can read contact requests"
on public.contact_requests for select
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can update contact requests" on public.contact_requests;
create policy "Admins can update contact requests"
on public.contact_requests for update
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid)
with check (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Admins can delete contact requests" on public.contact_requests;
create policy "Admins can delete contact requests"
on public.contact_requests for delete
to authenticated
using (auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid);

drop policy if exists "Public can read Elky media" on storage.objects;
create policy "Public can read Elky media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'elky-studios');

drop policy if exists "Admins can upload Elky media" on storage.objects;
create policy "Admins can upload Elky media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'elky-studios'
  and auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid
);

drop policy if exists "Admins can update Elky media" on storage.objects;
create policy "Admins can update Elky media"
on storage.objects for update
to authenticated
using (
  bucket_id = 'elky-studios'
  and auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid
)
with check (
  bucket_id = 'elky-studios'
  and auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid
);

drop policy if exists "Admins can delete Elky media" on storage.objects;
create policy "Admins can delete Elky media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'elky-studios'
  and auth.uid() = '69770c28-7c21-4edb-8656-9198fbd02df4'::uuid
);

commit;
